---
language: python
sudo: false

python:
  - '3.7'
  - '3.6'
  - '3.5'
  - '3.4'

install: virtualenv venv && source venv/bin/activate && pip install -r requirements.txt

script:
  - make test
  - make build
