---
language: python
sudo: false

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install invoke
  - pip install -r requirements.txt -r requirements-dev.txt

script:
  - invoke test
  - invoke build
